import type { Performance } from "@/types/firestore";
import type { ProjectionSetId } from "./projection";

export interface PerfWithId extends Partial<Performance> {
  id: string;
  name: string;
  departmentId: string;
}

export const SAMPLE_PERFORMANCES_BY_SET: Record<ProjectionSetId, PerfWithId[]> = {
  set1: [
    {
      id: "sample-it-dance",
      name: "IT — Dynamic Troupe",
      departmentId: "205",
      categoryId: "dance",
      participants: "Rhythm Troupe",
      description: "Fast-paced cinematic hip-hop fusion choreography",
      status: "completed",
      totalVotes: 185,
      averageRating: 4.74,
      percentageScore: 94.8,
      rating5Count: 140,
      rating4Count: 42,
      rating3Count: 3,
      rating2Count: 0,
      rating1Count: 0,
      order: 1,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-cse-dance",
      name: "CSE — Step Sync Crew",
      departmentId: "104",
      categoryId: "dance",
      participants: "Byte Breakers",
      description: "Synchronized robotic popping & contemporary formation",
      status: "completed",
      totalVotes: 172,
      averageRating: 4.56,
      percentageScore: 91.2,
      rating5Count: 110,
      rating4Count: 50,
      rating3Count: 10,
      rating2Count: 2,
      rating1Count: 0,
      order: 2,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-aids-dance",
      name: "AIDS — Pulse Dancers",
      departmentId: "243",
      categoryId: "dance",
      participants: "Neural Groovers",
      description: "High-energy cinematic electro-pop sequence",
      status: "completed",
      totalVotes: 160,
      averageRating: 4.4,
      percentageScore: 88.0,
      rating5Count: 85,
      rating4Count: 60,
      rating3Count: 12,
      rating2Count: 3,
      rating1Count: 0,
      order: 3,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-ece-dance",
      name: "ECE — Wave Shakers",
      departmentId: "106",
      categoryId: "dance",
      participants: "Frequency Troupe",
      description: "Contemporary classical & modern wave styling",
      status: "completed",
      totalVotes: 148,
      averageRating: 4.12,
      percentageScore: 82.4,
      rating5Count: 60,
      rating4Count: 55,
      rating3Count: 25,
      rating2Count: 6,
      rating1Count: 2,
      order: 4,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-mech-dance",
      name: "MECH — Beat Storm",
      departmentId: "114",
      categoryId: "dance",
      participants: "Gear Dancers",
      description: "Acrobatic stunts & high-impact group choreography",
      status: "completed",
      totalVotes: 139,
      averageRating: 3.93,
      percentageScore: 78.6,
      rating5Count: 45,
      rating4Count: 50,
      rating3Count: 35,
      rating2Count: 7,
      rating1Count: 2,
      order: 5,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-eee-dance",
      name: "EEE — Volt Steppers",
      departmentId: "105",
      categoryId: "dance",
      participants: "Current Squad",
      description: "Rhythmic step styling with visual light props",
      status: "completed",
      totalVotes: 125,
      averageRating: 3.7,
      percentageScore: 74.0,
      rating5Count: 30,
      rating4Count: 45,
      rating3Count: 35,
      rating2Count: 12,
      rating1Count: 3,
      order: 6,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-civil-dance",
      name: "CIVIL — Rhythm Builders",
      departmentId: "103",
      categoryId: "dance",
      participants: "Foundation Troupe",
      description: "Folk-western blend celebrating festival energy",
      status: "completed",
      totalVotes: 110,
      averageRating: 3.46,
      percentageScore: 69.2,
      rating5Count: 20,
      rating4Count: 38,
      rating3Count: 34,
      rating2Count: 14,
      rating1Count: 4,
      order: 7,
      createdAt: null as any,
      updatedAt: null as any,
    },
  ],
  set2: [
    {
      id: "sample-cse-singing",
      name: "CSE — Sonic Vocals",
      departmentId: "104",
      categoryId: "sing",
      participants: "Vocal Ensemble",
      description: "Acapella & polyphonic harmony melody",
      status: "completed",
      totalVotes: 180,
      averageRating: 4.76,
      percentageScore: 95.2,
      order: 1,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-it-singing",
      name: "IT — Melodic Harmony",
      departmentId: "205",
      categoryId: "sing",
      participants: "Duo Harmony",
      description: "Carnatic classical & western pop fusion medley",
      status: "completed",
      totalVotes: 165,
      averageRating: 4.6,
      percentageScore: 92.0,
      order: 2,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-ece-singing",
      name: "ECE — Acoustic Echoes",
      departmentId: "106",
      categoryId: "sing",
      participants: "Acoustic Soloist",
      description: "Soulful acoustic guitar & high vocal range",
      status: "completed",
      totalVotes: 155,
      averageRating: 4.47,
      percentageScore: 89.4,
      order: 3,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-mech-singing",
      name: "MECH — Iron Chords",
      departmentId: "114",
      categoryId: "sing",
      participants: "Vocal Band",
      description: "Classic rock & power anthem chorus",
      status: "completed",
      totalVotes: 140,
      averageRating: 4.18,
      percentageScore: 83.6,
      order: 4,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-aids-singing",
      name: "AIDS — Synth Harmonics",
      departmentId: "243",
      categoryId: "sing",
      participants: "Vocal Trio",
      description: "Modern jazz harmony with live looping",
      status: "completed",
      totalVotes: 132,
      averageRating: 4.02,
      percentageScore: 80.4,
      order: 5,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-civil-singing",
      name: "CIVIL — Heritage Voices",
      departmentId: "103",
      categoryId: "sing",
      participants: "Choir Quintet",
      description: "Traditional folk chorus & harmony arrangement",
      status: "completed",
      totalVotes: 120,
      averageRating: 3.82,
      percentageScore: 76.4,
      order: 6,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-eee-singing",
      name: "EEE — High Voltage Vocals",
      departmentId: "105",
      categoryId: "sing",
      participants: "Power Ballad Duo",
      description: "Dynamic ballad performance with orchestral backing",
      status: "completed",
      totalVotes: 112,
      averageRating: 3.64,
      percentageScore: 72.8,
      order: 7,
      createdAt: null as any,
      updatedAt: null as any,
    },
  ],
  set3: [
    {
      id: "sample-aids-inst",
      name: "AIDS — Symphony AI",
      departmentId: "243",
      categoryId: "instrumental",
      participants: "Electronic Synth & Violin",
      description: "Crossover electronic violin with custom synth pads",
      status: "completed",
      totalVotes: 190,
      averageRating: 4.8,
      percentageScore: 96.0,
      order: 1,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-it-inst",
      name: "IT — Cyber Strings Ensemble",
      departmentId: "205",
      categoryId: "instrumental",
      participants: "Guitar & Keyboard Trio",
      description: "Speed guitar fingerstyle & classical piano duel",
      status: "completed",
      totalVotes: 175,
      averageRating: 4.67,
      percentageScore: 93.4,
      order: 2,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-cse-inst",
      name: "CSE — Binary Beats Band",
      departmentId: "104",
      categoryId: "instrumental",
      participants: "Drums & Bass Collective",
      description: "Progressive syncopated drum solo & slap bass",
      status: "completed",
      totalVotes: 162,
      averageRating: 4.5,
      percentageScore: 90.0,
      order: 3,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-eee-inst",
      name: "EEE — Electric Fusion",
      departmentId: "105",
      categoryId: "instrumental",
      participants: "Flute & Electric Percussion",
      description: "Bamboo flute meets electronic ambient pads",
      status: "completed",
      totalVotes: 145,
      averageRating: 4.28,
      percentageScore: 85.6,
      order: 4,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-ece-inst",
      name: "ECE — Resonant Waves",
      departmentId: "106",
      categoryId: "instrumental",
      participants: "Keyboard & Saxophone",
      description: "Smooth jazz improvisation & chord melody",
      status: "completed",
      totalVotes: 135,
      averageRating: 4.05,
      percentageScore: 81.0,
      order: 5,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-civil-inst",
      name: "CIVIL — Concrete Percussion",
      departmentId: "103",
      categoryId: "instrumental",
      participants: "Acoustic Percussion Troupe",
      description: "Multi-drum rhythm ensemble & cajon beat breakdown",
      status: "completed",
      totalVotes: 125,
      averageRating: 3.86,
      percentageScore: 77.2,
      order: 6,
      createdAt: null as any,
      updatedAt: null as any,
    },
    {
      id: "sample-mech-inst",
      name: "MECH — Heavy Metal Ensemble",
      departmentId: "114",
      categoryId: "instrumental",
      participants: "Dual Lead Guitar Duo",
      description: "Heavy metal shredding & harmonized guitar leads",
      status: "completed",
      totalVotes: 118,
      averageRating: 3.65,
      percentageScore: 73.0,
      order: 7,
      createdAt: null as any,
      updatedAt: null as any,
    },
  ],
};
